### PR TITLE
Add support for building WebView with libwebkit2gtk-4.1

### LINKED ISSUE #23630: Build with libwebkit2gtk-4.1 and libsoup-3.0
### Description
Applications using wxWidgets and WebKit2GTK do not work with the latest runtime flatpak on Linux because the libwebkit2gtk-4.0 and libsoup-2.4 libraries have been removed. Only libwebkit2gtk-4.1 and libsoup-3.0 libraries are present. 

I really need the ability to build wxWidgets using libwebkit2gtk-4.1 and libsoup-3.0.

### PR DESCRIPTION
**Pull request by buzzhuzz**
libwebkit2gtk-4.1 has the same API as libwebkit2gtk-4.0, except that the former links with libsoup-3.0 and the latter links with libsoup-2.4.

Fixes #23630.

Cherry-picked https://github.com/wxWidgets/wxWidgets/commit/1b8664426603376b68f8ca3c54de97ec630e5940

configure is auto generated by running ```autoconf -i -f```

### CODE REVIEW

**Comment by powpingdone** [comment]
@SoftFever if this is in the pipeline, then this will have to be used for flatpak, and as such is a blocker for https://github.com/SoftFever/OrcaSlicer/pull/4175

**Comment by SoftFever** [comment]
@powpingdone 
Do you mind explaining a bit more about why it will block the WIP flatpack pipeline?

**Comment by powpingdone** [comment]
@SoftFever The internal libwebkit2gtk used in the flatpak runtime uses 4.1+. It's needed in order to build. (This is not a blocker for the flatpak, but the flatpak is blocked on this pr, and is waiting for this to be merged.)

**Comment by SoftFever** [comment]
Thank you @buzzhuzz 
Looks good

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
